CREATE OR REPLACE VIEW V_USER_ALL AS
SELECT "USER_ID","SYSTEM_TYPE","USER_KIND","EMP_NO","DEPT_CODE","DEPT_NAME","OFFICE_CODE","EMP_HNAME","EMP_ENAME","EMP_CNAME","MAIL_ADDR","HT_CODE","LOGIN_ID","LOGIN_PW","USE_YN" FROM (
SELECT A.USER_ID
     , A.SYSTEM_TYPE
     , CASE WHEN B.USER_ID IS NOT NULL THEN 'INT'
            WHEN C.USER_ID IS NOT NULL THEN 'OUT'
            WHEN D.USER_ID IS NOT NULL THEN 'OFF'
       END USER_KIND
     , CASE WHEN B.USER_ID IS NOT NULL THEN B.EMP_NO
            WHEN C.USER_ID IS NOT NULL THEN C.EMP_NO
            WHEN D.USER_ID IS NOT NULL THEN D.EMP_NO
       END EMP_NO
     , CASE WHEN B.USER_ID IS NOT NULL THEN B.DEPT_CODE
       END DEPT_CODE
     , CASE WHEN B.USER_ID IS NOT NULL THEN FN_DEPT_NAME(B.DEPT_CODE)
            WHEN C.USER_ID IS NOT NULL THEN C.DEPT_NAME
            WHEN D.USER_ID IS NOT NULL THEN D.DEPT_NAME
       END DEPT_NAME
     , CASE WHEN D.USER_ID IS NOT NULL THEN D.OFFICE_CODE
       END OFFICE_CODE
     , A.EMP_HNAME
     , A.EMP_ENAME
     , A.EMP_CNAME
     , A.MAIL_ADDR
     , A.HT_CODE
     , A.LOGIN_ID
     , A.LOGIN_PW
     , A.USE_YN
FROM   TB_USR_MST A
     , TB_USR_PATENT B
     , TB_USR_OUT_INVENTOR C
     , TB_USR_OFFICE D
WHERE  A.USER_ID = B.USER_ID(+)
AND    A.USER_ID = C.USER_ID(+)
AND    A.USER_ID = D.USER_ID(+)
) T;
