CREATE OR REPLACE FUNCTION FN_COUNTRY_NAME
(
    I_COUNTRY_CODE              IN  TB_COM_COUNTRY.COUNTRY_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_COM_COUNTRY.COUNTRY_NAME%TYPE;

BEGIN

    SELECT COUNTRY_NAME
    INTO   R_TEXT
    FROM   TB_COM_COUNTRY
    WHERE  COUNTRY_CODE = I_COUNTRY_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_COUNTRY_CODE;

END;
