CREATE OR REPLACE FUNCTION FN_COM_CODE_NAME
(
    I_CODE_GRP_ID               IN  TB_COM_CODE_GRP.CODE_GRP_ID%TYPE
  , I_CODE_VALUE_ID             IN  TB_COM_CODE_VALUE.CODE_VALUE_ID%TYPE
  , I_LANG_CODE                 IN  TB_COM_CODE_NAME.LANG_CODE%TYPE
  , I_DEFAULT_LANG_CODE         IN  TB_COM_CODE_NAME.LANG_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_COM_CODE_NAME.CODE_NAME%TYPE;

    V_CODE_GRP                  TB_COM_CODE_GRP.CODE_GRP%TYPE;
    V_CODE_VALUE                TB_COM_CODE_VALUE.CODE_VALUE%TYPE;

BEGIN

    SELECT CODE_GRP
    INTO   V_CODE_GRP
    FROM   TB_COM_CODE_GRP
    WHERE  CODE_GRP_ID = I_CODE_GRP_ID
    ;

    SELECT CODE_VALUE
    INTO   V_CODE_VALUE
    FROM   TB_COM_CODE_VALUE
    WHERE  CODE_GRP = V_CODE_GRP
    AND    CODE_VALUE_ID = I_CODE_VALUE_ID
    ;

    SELECT CODE_NAME
    INTO   R_TEXT
    FROM   TB_COM_CODE_NAME
    WHERE  CODE_GRP = V_CODE_GRP
    AND    CODE_VALUE = V_CODE_VALUE
    AND    LANG_CODE = I_LANG_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            IF I_DEFAULT_LANG_CODE IS NOT NULL AND I_LANG_CODE <> I_DEFAULT_LANG_CODE THEN
                RETURN FN_COM_CODE_NAME(I_CODE_GRP_ID, I_CODE_VALUE_ID, I_DEFAULT_LANG_CODE, NULL);
            END IF;
            RETURN I_CODE_VALUE_ID;

END;
