CREATE OR REPLACE FUNCTION FN_COUNTRY_NAMES
(
    I_REF_ID                    IN  TB_MAPP_COUNTRY.REF_ID%TYPE
)
RETURN VARCHAR2 IS R_TEXT VARCHAR2(4000);

    CURSOR C1 IS
    SELECT B.COUNTRY_NAME
    FROM   TB_MAPP_COUNTRY A
         , TB_COM_COUNTRY B
    WHERE  A.REF_ID = I_REF_ID
    AND    A.COUNTRY_CODE = B.COUNTRY_CODE
    ORDER  BY B.DISP_ORD
    ;

BEGIN

    FOR R1 IN C1 LOOP
        IF LENGTH(R_TEXT) > 0 THEN
            R_TEXT := R_TEXT || ',';
        END IF;
        R_TEXT := R_TEXT || R1.COUNTRY_NAME;
    END LOOP;

    RETURN R_TEXT;

END;
