CREATE OR REPLACE FUNCTION FN_DEPT_NAME
(
    I_DEPT_CODE                 IN  TB_ORG_DEPT.DEPT_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_ORG_DEPT.DEPT_NAME%TYPE;

BEGIN

    SELECT DEPT_NAME
    INTO   R_TEXT
    FROM   TB_ORG_DEPT
    WHERE  DEPT_CODE = I_DEPT_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_DEPT_CODE;

END;
