CREATE OR REPLACE FUNCTION FN_DIVISN_NAME
(
    I_DIVISN_CODE               IN  TB_ORG_DIVISN.DIVISN_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_ORG_DIVISN.DIVISN_NAME%TYPE;

BEGIN

    SELECT DIVISN_NAME
    INTO   R_TEXT
    FROM   TB_ORG_DIVISN
    WHERE  DIVISN_CODE = I_DIVISN_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_DIVISN_CODE;

END;
