CREATE OR REPLACE FUNCTION FN_GRP_NO
(
    I_GRP_ID                    IN  TB_APP_EXT_GRP.GRP_ID%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_APP_EXT_GRP.GRP_NO%TYPE;

BEGIN

    SELECT GRP_NO
    INTO   R_TEXT
    FROM   TB_APP_EXT_GRP
    WHERE  GRP_ID = I_GRP_ID
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_GRP_ID;

END;
