CREATE OR REPLACE FUNCTION FN_INV_APPLY_ACTUAL
/**
 * 건당 발명자별 실적 값 반환
 */
(
    I_REF_ID                    IN  TB_MAPP_INVENTOR.REF_ID%TYPE
  , I_INV_USER                  IN  TB_MAPP_INVENTOR.INV_USER%TYPE
)
RETURN NUMBER IS R_VALUE NUMBER(3,2);

    V_MAIN_INVENTOR_YN          TB_MAPP_INVENTOR.MAIN_INVENTOR_YN%TYPE;
    V_INV_COUNT                 NUMBER;
    V_ACT_RATIO                 NUMBER;

BEGIN

    SELECT MAIN_INVENTOR_YN
    INTO   V_MAIN_INVENTOR_YN
    FROM   TB_MAPP_INVENTOR
    WHERE  REF_ID = I_REF_ID
    AND    INV_USER = I_INV_USER
    ;

    SELECT COUNT(1)
    INTO   V_INV_COUNT
    FROM   TB_MAPP_INVENTOR
    WHERE  REF_ID = I_REF_ID
    ;

    V_ACT_RATIO := TRUNC(1 / V_INV_COUNT, 2);

    IF V_MAIN_INVENTOR_YN = '1' THEN
        R_VALUE := 1 - V_ACT_RATIO * (V_INV_COUNT - 1);
    ELSE
        R_VALUE := V_ACT_RATIO;
    END IF
    ;

    RETURN R_VALUE;

    EXCEPTION
        WHEN OTHERS THEN
            RETURN NULL;

END;
