CREATE OR REPLACE FUNCTION FN_LAB_NAME
(
    I_LAB_CODE                  IN  TB_ORG_LAB.LAB_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_USR_MST.EMP_HNAME%TYPE;

BEGIN

    SELECT LAB_NAME
    INTO   R_TEXT
    FROM   TB_ORG_LAB
    WHERE  LAB_CODE = I_LAB_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_LAB_CODE;

END;
