CREATE OR REPLACE FUNCTION FN_OFFICE_NAME
(
    I_OFFICE_CODE               IN  TB_ORG_OFFICE.OFFICE_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_USR_MST.EMP_HNAME%TYPE;

BEGIN

    SELECT FIRM_HNAME
    INTO   R_TEXT
    FROM   TB_ORG_OFFICE
    WHERE  OFFICE_CODE = I_OFFICE_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_OFFICE_CODE;

END;
