CREATE OR REPLACE FUNCTION FN_PAPER_NAME
(
    I_PAPER_CODE                IN  TB_PAPER_MGT_MST.PAPER_CODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_PAPER_MGT_MST.PAPER_NAME%TYPE;

BEGIN

    SELECT PAPER_NAME
    INTO   R_TEXT
    FROM   TB_PAPER_MGT_MST
    WHERE  PAPER_CODE = I_PAPER_CODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_PAPER_CODE;

END;
