CREATE OR REPLACE FUNCTION FN_PAPER_SUBNAME
(
    I_PAPER_CODE                IN  TB_PAPER_MGT_SUB.PAPER_CODE%TYPE
  , I_PAPER_SUBCODE             IN  TB_PAPER_MGT_SUB.PAPER_SUBCODE%TYPE
)
RETURN VARCHAR2 IS R_TEXT TB_PAPER_MGT_SUB.PAPER_SUBNAME%TYPE;

BEGIN

    SELECT PAPER_SUBNAME
    INTO   R_TEXT
    FROM   TB_PAPER_MGT_SUB
    WHERE  PAPER_CODE = I_PAPER_CODE
    AND    PAPER_SUBCODE = I_PAPER_SUBCODE
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN I_PAPER_CODE;

END;
