CREATE OR REPLACE FUNCTION FN_RIVALPAT_TECH_NAMES
(
    I_MGT_ID                    IN  TB_RIVALPAT_MAPP_TECH_CLS.MGT_ID%TYPE
)
RETURN VARCHAR2 IS R_TEXT VARCHAR2(4000);

    CURSOR C1 IS
    SELECT B.TECH_HNAME
    FROM   TB_RIVALPAT_MAPP_TECH_CLS A
         , TB_COM_TECH_CLS B
    WHERE  A.MGT_ID = I_MGT_ID
    AND    A.TECH_CODE = B.TECH_CODE(+)
    ORDER BY A.MAIN_CLS_YN DESC, B.TECH_HNAME
    ;

BEGIN

    FOR R1 IN C1 LOOP
        IF LENGTH(R_TEXT) > 0 THEN
            R_TEXT := R_TEXT || ', ';
        END IF;
        R_TEXT := R_TEXT || R1.TECH_HNAME;
    END LOOP;

    RETURN R_TEXT;

END;
