CREATE OR REPLACE FUNCTION FN_USER_EMPNO
(
    I_USER_ID                   IN  TB_USR_MST.USER_ID%TYPE
)
RETURN VARCHAR2 IS R_TEXT V_USER_ALL.EMP_NO%TYPE;

BEGIN

    SELECT EMP_NO
    INTO   R_TEXT
    FROM   V_USER_ALL
    WHERE  USER_ID = I_USER_ID
    ;

    RETURN R_TEXT;

    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN NULL;

END;
