/*
SELECT * FROM TB_SYS_SEQUENCE;

DELETE FROM TB_SYS_SEQUENCE;
*/

INSERT INTO TB_SYS_SEQUENCE
SELECT * FROM (
SELECT 'FILE_ID' SEQ_TYPE
     , 'FILE_ID' SEQ_HEADER
     , MAX(TO_NUMBER(FILE_ID)) SEQ_NO
FROM   TB_COM_FILE
UNION ALL
SELECT 'MAIL_ID' SEQ_TYPE
     , 'MAIL_ID' SEQ_HEADER
     , MAX(TO_NUMBER(MAIL_ID)) SEQ_NO
FROM   TB_MAIL_MST
UNION ALL
SELECT 'USER_ID' SEQ_TYPE
     , 'F' SEQ_HEADER
     , TO_NUMBER(SUBSTR(MAX(USER_ID), 2)) SEQ_NO
FROM   TB_USR_MST
WHERE  USER_ID LIKE 'F%'
UNION ALL
SELECT 'USER_ID' SEQ_TYPE
     , 'X' SEQ_HEADER
     , TO_NUMBER(SUBSTR(MAX(USER_ID), 2)) SEQ_NO
FROM   TB_USR_MST
WHERE  USER_ID LIKE 'X%'
UNION ALL
SELECT 'BIZ_ID' SEQ_TYPE
     , 'BIZ_ID' SEQ_HEADER
     , MAX(TO_NUMBER(BIZ_ID)) SEQ_NO
FROM   (SELECT MAX(REF_ID) BIZ_ID
        FROM   TB_APP_MST
        UNION ALL
        SELECT MAX(GRP_ID)
        FROM   TB_APP_EXT_GRP
        UNION ALL
        SELECT MAX(OL_ID)
        FROM   TB_APP_EXT_OL
        UNION ALL
        SELECT MAX(PRSCH_ID)
        FROM   TB_APP_PRSCH_REQ
        UNION ALL
        SELECT MAX(REF_ID)
        FROM   TB_APP_INT_REQ
        UNION ALL
        SELECT MAX(EVAL_ID)
        FROM   TB_EVAL_COM_MST
       )
UNION ALL
SELECT 'BIZ_HIST_SEQ' SEQ_TYPE
     , REF_ID SEQ_HEADER
     , MAX(TO_NUMBER(HIST_SEQ)) SEQ_NO
FROM   TB_BIZ_COM_HIST
GROUP BY REF_ID
UNION ALL
SELECT 'PAPER_LIST' SEQ_TYPE
     , REF_ID SEQ_HEADER
     , MAX(TO_NUMBER(LIST_SEQ)) SEQ_NO
FROM   TB_PAPER_LIST
GROUP BY REF_ID
UNION ALL
SELECT 'OA_SEQ' SEQ_TYPE
     , REF_ID SEQ_HEADER
     , MAX(TO_NUMBER(OA_SEQ)) SEQ_NO
FROM   TB_OA_HIST
GROUP BY REF_ID
UNION ALL
SELECT 'GRAND_CODE' SEQ_TYPE
     , 'GRAND_CODE' SEQ_HEADER
     , MAX(TO_NUMBER(GRAND_CODE)) SEQ_NO
FROM   TB_COST_MGT_GRANDCODE
UNION ALL
SELECT 'DETAIL_CODE' SEQ_TYPE
     , GRAND_CODE SEQ_HEADER
     , MAX(TO_NUMBER(DETAIL_CODE)) SEQ_NO
FROM   TB_COST_MGT_DETAILCODE
GROUP BY GRAND_CODE
UNION ALL
SELECT 'OFFICE_CODE' SEQ_TYPE
     , 'OFFICE_CODE' SEQ_HEADER
     , MAX(TO_NUMBER(OFFICE_CODE)) SEQ_NO
FROM   TB_ORG_OFFICE
UNION ALL
SELECT 'MENU_CODE' SEQ_TYPE
     , SYSTEM_TYPE SEQ_HEADER
     , MAX(TO_NUMBER(MENU_CODE)) SEQ_NO
FROM   TB_MNU_MENU
GROUP BY SYSTEM_TYPE
UNION ALL
SELECT 'APPR_NO' SEQ_TYPE
     , 'APPR_NO' SEQ_HEADER
     , MAX(TO_NUMBER(APPR_NO)) SEQ_NO
FROM   TB_APPR_MST
UNION ALL
SELECT 'APPR_REQ_SEQ' SEQ_TYPE
     , APPR_NO SEQ_HEADER
     , MAX(TO_NUMBER(REQ_SEQ)) SEQ_NO
FROM   TB_APPR_REQ
GROUP BY APPR_NO
UNION ALL
SELECT 'EVAL_SHEET_ID' SEQ_TYPE
     , 'EVAL_SHEET_ID' SEQ_HEADER
     , MAX(TO_NUMBER(EVAL_SHEET_ID)) SEQ_NO
FROM   TB_EVAL_SHEET_MAIN
UNION ALL
SELECT 'BRD_NO' SEQ_TYPE
     , BRD_ID SEQ_HEADER
     , MAX(TO_NUMBER(BRD_NO)) SEQ_NO
FROM   TB_BRD_LIST
GROUP BY BRD_ID
UNION ALL
SELECT 'COST_SEQ' SEQ_TYPE
     , 'COST_SEQ' SEQ_HEADER
     , MAX(TO_NUMBER(COST_SEQ)) SEQ_NO
FROM   TB_COST_MST
WHERE  SUBSTR(COST_SEQ, 1, 2) = '00'
UNION ALL
SELECT 'LETTER_SEQ' SEQ_TYPE
     , 'LETTER_SEQ' SEQ_HEADER
     , MAX(TO_NUMBER(LETTER_SEQ)) SEQ_NO
FROM   TB_COST_EXT_LETTER
UNION ALL
SELECT 'PRSCH_NO' SEQ_TYPE
     , SUBSTR(PRSCH_NO, 2, 6) SEQ_HEADER
     , TO_NUMBER(SUBSTR(MAX(PRSCH_NO), 9)) SEQ_NO
FROM   TB_APP_PRSCH_REQ
GROUP BY SUBSTR(PRSCH_NO, 2, 6)
UNION ALL
SELECT 'REF_GRP_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(REF_NO, 1, INSTR(REF_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(REF_NO, INSTR(REF_NO, '-') + 1) SEQ_NO
        FROM   (SELECT REF_NO
                FROM   TB_APP_INT_REQ
                UNION ALL
                SELECT GRP_NO
                FROM   TB_APP_EXT_GRP
               )
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
UNION ALL
SELECT 'REF_GRP_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(MGT_NO, 1, INSTR(MGT_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(MGT_NO, INSTR(MGT_NO, '-') + 1) SEQ_NO
        FROM   TB_IPB_ANALY
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
UNION ALL
SELECT 'LICENSE_MGT_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(MGT_NO, 1, INSTR(MGT_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(MGT_NO, INSTR(MGT_NO, '-') + 1) SEQ_NO
        FROM   TB_IPB_LICENSE
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
UNION ALL
SELECT 'EXPOPIN_MGT_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(MGT_NO, 1, INSTR(MGT_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(MGT_NO, INSTR(MGT_NO, '-') + 1) SEQ_NO
        FROM   TB_IPB_EXPOPIN
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
UNION ALL
SELECT 'DISPUTE_MGT_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(MGT_NO, 1, INSTR(MGT_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(MGT_NO, INSTR(MGT_NO, '-') + 1) SEQ_NO
        FROM   TB_IPB_DISPUTE
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
UNION ALL
SELECT 'IP_BIZ_HIST_SEQ' SEQ_TYPE
     , REF_ID SEQ_HEADER
     , MAX(TO_NUMBER(HIST_SEQ)) SEQ_NO
FROM   TB_IPB_COM_HIST
GROUP BY REF_ID
UNION ALL
SELECT 'RIVALPAT_MGT_ID' SEQ_TYPE
     , 'RIVALPAT_MGT_ID' SEQ_HEADER
     , MAX(TO_NUMBER(MGT_ID)) SEQ_NO
FROM   TB_RIVALPAT_MST
UNION ALL
SELECT 'RIVALPAT_REPLY_SEQ' SEQ_TYPE
     , MGT_ID SEQ_HEADER
     , MAX(TO_NUMBER(REPLY_SEQ)) SEQ_NO
FROM   TB_RIVALPAT_REPLY
GROUP BY MGT_ID
UNION ALL
SELECT 'PROGRAM_NO' SEQ_TYPE
     , SEQ_HEADER
     , MAX(TO_NUMBER(SEQ_NO)) SEQ_NO
FROM   (SELECT SUBSTR(REF_NO, 1, INSTR(REF_NO, '-') - 1) SEQ_HEADER
             , SUBSTR(REF_NO, INSTR(REF_NO, '-') + 1) SEQ_NO
        FROM   TB_PROG_REQ
       )
WHERE  FN_IS_NUMBER(SEQ_NO) = '1'
GROUP BY SEQ_HEADER
) SEQ
WHERE  SEQ_NO IS NOT NULL
AND    NOT EXISTS (SELECT 1
                   FROM   TB_SYS_SEQUENCE X
                   WHERE  X.SEQ_TYPE = SEQ.SEQ_TYPE
                   AND    X.SEQ_HEADER = SEQ.SEQ_HEADER
                  )
;
