DROP SEQUENCE SQ_LOG_SEQ ;

CREATE SEQUENCE SQ_LOG_SEQ;

DROP TABLE TB_USR_LOG CASCADE CONSTRAINTS;

CREATE TABLE TB_USR_LOG (
       LOG_SEQ              INTEGER NOT NULL,
       SYSTEM_TYPE          VARCHAR2(10) NOT NULL,
       USER_ID              VARCHAR2(10) NULL,
       LOG_TYPE             CHAR(1) NOT NULL,
       LOG_DATE             VARCHAR2(8) NOT NULL,
       LOG_DATETIME         DATE NOT NULL,
       CLIENT_IP            VARCHAR2(15) NOT NULL,
       SERVER_IP            VARCHAR2(15) NOT NULL,
       REFERER_URL          VARCHAR2(2000) NULL,
       SERVLET_PATH         VARCHAR2(1000) NULL,
       ERROR_YN             CHAR(1) NOT NULL,
       ERROR_MSG            LONG VARCHAR NULL
);

COMMENT ON TABLE TB_USR_LOG IS '사용자 로그';
COMMENT ON COLUMN TB_USR_LOG.LOG_SEQ IS '로그 Sequence';
COMMENT ON COLUMN TB_USR_LOG.SYSTEM_TYPE IS '시스템형태(PATENT/OFFICE)';
COMMENT ON COLUMN TB_USR_LOG.USER_ID IS '사용자 ID';
COMMENT ON COLUMN TB_USR_LOG.LOG_TYPE IS '로그형태(0:접속로그, 1:사용로그)';
COMMENT ON COLUMN TB_USR_LOG.LOG_DATE IS '로그일자(YYYYMMDD)';
COMMENT ON COLUMN TB_USR_LOG.LOG_DATETIME IS '로그일시(DATETIME)';
COMMENT ON COLUMN TB_USR_LOG.CLIENT_IP IS '클라이언트 IP';
COMMENT ON COLUMN TB_USR_LOG.SERVER_IP IS '서버 IP';
COMMENT ON COLUMN TB_USR_LOG.REFERER_URL IS '요청페이지 URL';
COMMENT ON COLUMN TB_USR_LOG.SERVLET_PATH IS '서블릿 경로';
COMMENT ON COLUMN TB_USR_LOG.ERROR_YN IS '에러여부(1/0)';
COMMENT ON COLUMN TB_USR_LOG.ERROR_MSG IS '에러메세지';
CREATE UNIQUE INDEX XPKTB_USR_LOG ON TB_USR_LOG
(
       LOG_SEQ                        ASC
);

CREATE INDEX XIE1TB_USR_LOG ON TB_USR_LOG
(
       LOG_TYPE                       ASC,
       LOG_DATE                       ASC
);


ALTER TABLE TB_USR_LOG
       ADD CONSTRAINT XPKTB_USR_LOG PRIMARY KEY (LOG_SEQ);
